### ISSUE TITLE
background folder

### ISSUE THREAD

**Issue by dannypa27** [alejopc03/cr-plates-generator#1]
Trying to run your code, but says its missing a folder called backgrounds.  Did you leave out a folder?

The templates folder is there.  Thanks for any help.  

I appreciate the work you did writing this.

--danny

**Comment by apereiracv** [comment]
Thank you for your interest in this code! To answer your question:
For now, you need to create this folder as './backgrounds' and add to all the images that you want to use as background to randomly place the plate.

Alternatively you can change the `backgrounds_path` setting inside "configuration.cfg" to point to where you have your own background images.

Finally, I'd like to tell you that this project is WIP and very early, there are a lot of settings and functionality missing that I will be adding in the near future.

I'm glad that you find this useful, I would like to also know about your interest in generating Costa Rica plates, are you from CR?

**Comment by dannypa27** [comment]
Thank you for your quick response.  

I'm from West Virginia, USA.  I'm a graduate student taking Pattern Recognition at WVU.  I'm doing a project involving deep learning in which we are reading license plates.  I'm trying to generate various types of plates to use as our datasets.  

Once again, I appreciate your work on this code, sharing your code and your fast response to my question.

--danny

**Comment by apereiracv** [comment]
Oh I see, that's very nice, good luck with your project! If you're able to share it once it is finished I would like to take a look  :)

I am updating this project when I can, I just added bounding box funcionality if you want to check it out.

-Alejandro
